parameters:

  assets_backup.class:       dmAssetsBackupService

services:

  assets_backup:
    class:                %assets_backup.class%
    shared:               true
    arguments:            [ @user, @filesystem ]